name: CI

on:
  push:
    branches:
      - main
      - feature/docker
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Dockerfile
        run: docker build -t devops-intern-nginx -f app/Dockerfile .